config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'houses#index'

  resources :houses
  resources :house_bookings, only: %i[create destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
# frozen_string_literal: true

class House < ApplicationRecord
  has_many :house_bookings, dependent: :destroy

  validates(:name, :country, :city, presence: true)
  validates(:price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999_999.99 })

  def last_check_out_date
    house_bookings.from_check_out_date(Date.current).order(check_out: :desc).first&.check_out
  end

  def first_check_in_date
    house_bookings.from_check_in_date(Date.current).order(check_in: :asc).first&.check_in
  end
end

app/models/house_booking.rb
# frozen_string_literal: true

class HouseBooking < ApplicationRecord
  belongs_to :house

  validate :validate_dates

  scope :from_check_in_date, ->(date) { where(check_in: date..) }
  scope :from_check_out_date, ->(date) { where(check_out: date..) }

  private

  def validate_dates
    errors.add(:base, :wrong_dates) if check_in >= check_out
    errors.add(:base, :already_booked) if house.house_bookings.where(check_out: check_in..).present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/house_bookings_controller.rb
# frozen_string_literal: true

class HouseBookingsController < ApplicationController
  def create
    @booking = HouseBooking.new(booking_params)
    if @booking.save
      redirect_to house_url(@booking.house)
    else
      head(:unprocessable_entity)
    end
  end

  def destroy
    @booking = HouseBooking.find(params[:id])

    house = @booking.house

    @booking.destroy
    redirect_to house_url(house)
  end

  private

  def booking_params
    params.require(:house_booking).permit(:house_id, :check_in, :check_out)
  end
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  before_action :set_house, only: %i[show edit update destroy]
  before_action :assign_filters, only: :index

  def index
    @houses = HousesSearchService.filter_houses(@filters)
  end

  def show
    @bookings = @house.house_bookings.from_check_out_date(Date.current)
  end

  def new
    @house = House.new
  end

  def edit; end

  def create
    @house = House.new(house_params)

    if @house.save
      redirect_to house_url(@house), notice: 'House was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @house.update(house_params)
      redirect_to house_url(@house), notice: 'House was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @house.destroy

    redirect_to houses_url, notice: 'House was successfully destroyed.'
  end

  private

  def set_house
    @house = House.find(params[:id])
  end

  def house_params
    params.require(:house).permit(:country, :city, :name, :description, :address, :price)
  end

  def assign_filters
    @country = params[:country]
    @city = params[:city]
    @check_in = params[:check_in]
    @check_out = params[:check_out]

    @filters = { country: @country, city: @city, check_in: @check_in, check_out: @check_out }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/houses_helper.rb
# frozen_string_literal: true

module HousesHelper
  def check_in_range(house)
    cur_date = Date.current
    { min: ((house.last_check_out_date || cur_date) + 1.days), max: (cur_date + 1.year) }
  end

  def check_out_range(house)
    cur_date = Date.current
    { min: ((house.last_check_out_date || cur_date) + 2.days), max: (cur_date + 1.year) }
  end
end

app/views/houses/_form.html.erb
<div>
  <%= form_with(model: house, local: true) do |form| %>
    <% if house.errors.any? %>
      <div class="error-explanation">
        <div class="h4"><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</div>

        <ul>
          <% house.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="cell">
      <%= form.label(:country, class: 'form-label') %>
      <%= form.text_field(:country, class: 'form-control') %>
    </div>

    <div class="cell">
      <%= form.label(:city, class: 'form-label') %>
      <%= form.text_field(:city, class: 'form-control') %>
    </div>

    <div class="cell">
      <%= form.label(:address, class: 'form-label') %>
      <%= form.text_field(:address, class: 'form-control') %>
    </div>

    <div class="cell">
      <%= form.label(:name, class: 'form-label') %>
      <%= form.text_field(:name, class: 'form-control') %>
    </div>

    <div class="cell">
      <%= form.label(:description, class: 'form-label') %>
      <%= form.text_area(:description, class: 'form-control') %>
    </div>

    <div class="cell">
      <div class="form-label">
        Price per night in $
      </div>
      <%= form.text_field(:price, class: 'form-control') %>
    </div>

    <div class="cell">
      <%= form.submit(class: 'btn btn-success') %>
    </div>
  <% end %>
</div>

app/views/houses/_house_row.html.erb
<div class="house-row-grid house-row">
  <div></div>

  <div class="house-info">
    <div class="cell house-name">
      <%= link_to(house.name, house) %>
    </div>

    <div class="cell house-location">
      <%= house.country %>, <%= house.city %>
    </div>

    <div class="cell house-description wrap-anywhere">
      <%= house.description.truncate(140) %>
    </div>

    <div class="cell house-price">
      <%= house.price %> $
    </div>
  </div>
</div>

app/views/houses/edit.html.erb
<div class="container">
  <%= link_to 'Show', @house %> |
  <%= link_to 'Back', houses_path %>

  <div class="h1">
    Editing House '<%= @house.name %>'
  </div>

  <%= render 'form', house: @house %>
</div>

app/views/houses/index.html.erb
<div class="container">
  <%= render('partials/search_bar') %>
</div>

<div class="container">
  <p id="notice"><%= notice %></p>

  <% if @houses.present? %>
    <div class="h3">Available houses</div>
  <% else %>
    <div class="h2">Sorry there is no houses</div>
  <% end %>

  <%= render(partial: 'house_row', collection: @houses, as: :house) %>

  <br>

  <%= link_to 'New House', new_house_path %>

</div>

app/views/houses/new.html.erb
<div class="container">
  <%= link_to 'Back', houses_path %>

  <div class="h1">New House</div>

  <%= render 'form', house: @house %>
</div>

app/views/houses/show.html.erb
<div class="container">
  <%= link_to 'Edit', edit_house_path(@house) %> |
  <%= link_to 'Back', houses_path %>

  <p id="notice"><%= notice %></p>

  <div class="house-detailed-container item-border">
    <div class="house-general-info">
      <div class="cell">
        <%= @house.country %>, <%= @house.city %>
      </div>

      <div class="cell h2">
        <%= @house.name %>
      </div>

      <div class="cell wrap-anywhere">
        <%= @house.description || 'House without description' %>
      </div>
    </div>
    <div class="house-book-window item-border">
      <div class="cell">
        <strong>Price:</strong>
        <%= @house.price %> $ / per night
      </div>

      <div>
        <div class="booking-form">
          <%= form_with(model: HouseBooking.new) do |form| %>
            <%= form.hidden_field(:house_id, value: @house.id) %>
            <div class="house-booking-form-grid">
              <div class="cell">
                <%= form.label(:check_in, class: 'form-label') %>
                <%= form.date_field(:check_in, class: 'form-control', min: check_in_range(@house)[:min], max: check_in_range(@house)[:max])  %>
              </div>

              <div class="cell">
                <%= form.label(:check_out, class: 'form-label') %>
                <%= form.date_field(:check_out, class: 'form-control', min: check_out_range(@house)[:min], max: check_out_range(@house)[:max]) %>
              </div>

              <div class="cell">
                <%= form.submit('Book house', class: 'btn btn-success') %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="house-existing_booking-grid">
          <% if @bookings.present? %>
            <div>
              Already booked from:
            </div>

            <div>
              To:
            </div>

            <div></div>

            <% @bookings.each do |booking| %>
              <div>
                <%= booking.check_in %>
              </div>

              <div>
                <%= booking.check_out %>
              </div>

              <div>
                <%= link_to('X', house_booking_url(booking), method: :delete) %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>airbnb_replication_for_inteview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mt-2 mb-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_search_bar.html.erb
<div>
  <%= form_with(url: houses_path, method: :get, local: true) do |f| %>
    <div class="row item-border cell">
      <div class="col-md-7">
        <div class="col">Where are you going?</div>

        <div class="row">
          <div class="col form-group">
            Country: <%= f.text_field(:country, value: @country, placeholder: 'Germany', class: 'form-control-sm') %>
          </div>

          <div class="col form-group">
            City: <%= f.text_field(:city, value: @city, placeholder: 'Berlin', class: 'form-control-sm') %>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="column">
          <div class="col">Check in</div>

          <div class="col">
            <%= f.date_field(:check_in, value: @check_in, class: 'form-control-sm', min: Date.current) %>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="column">
          <div class="col">Check out</div>

          <div class="col">
            <%= f.date_field(:check_out, value: @check_out, class: 'form-control-sm', min: Date.current) %>
          </div>
        </div>
      </div>

      <div class="col align-self-end">
        <%= f.submit('Search') %>
      </div>
    </div>
  <% end %>
</div>